"use client";

import { useEffect, useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { 
  FileDown, 
  BarChart3, 
  TrendingUp, 
  ShieldAlert, 
  AlertCircle,
  Download
} from "lucide-react";

interface Report {
  id: string;
  companyName: string;
  date: string;
  healthScore: number;
  zScore: number;
  investmentScore: number;
  riskLevel: string;
}

export default function ReportsPage() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Load all reports from localStorage
    try {
      const storedReports = localStorage.getItem("finhealth_reports");
      if (storedReports) {
        const allReports = JSON.parse(storedReports);
        setReports(allReports);
      }
    } catch (error) {
      console.error("Failed to load reports:", error);
    }
    setLoading(false);
  }, []);

  const getRiskColor = (riskLevel: string) => {
    switch (riskLevel?.toLowerCase()) {
      case "high risk":
      case "high":
        return "destructive";
      case "medium risk":
      case "medium":
        return "secondary";
      case "low risk":
      case "low":
        return "default";
      default:
        return "outline";
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 70) return "text-green-600 dark:text-green-400";
    if (score >= 50) return "text-yellow-600 dark:text-yellow-400";
    return "text-red-600 dark:text-red-400";
  };

  const downloadReport = (report: Report) => {
    const content = `
Financial Report - ${report.companyName}
Generated: ${report.date}
=====================================

HEALTH SCORE: ${report.healthScore.toFixed(2)}/100
Z-SCORE (Bankruptcy Risk): ${report.zScore.toFixed(2)}
INVESTMENT SCORE: ${report.investmentScore.toFixed(2)}/100
RISK LEVEL: ${report.riskLevel}

This report was generated by FinHealth AI
    `;
    
    const element = document.createElement("a");
    element.setAttribute("href", "data:text/plain;charset=utf-8," + encodeURIComponent(content));
    element.setAttribute("download", `${report.companyName}-report-${report.date}.txt`);
    element.style.display = "none";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="flex-1 space-y-6 p-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">Financial Reports</h1>
        <p className="text-muted-foreground mt-2">
          View and manage all historical analyses and company reports.
        </p>
      </div>

      {loading ? (
        <Card>
          <CardContent className="pt-6">
            <p className="text-muted-foreground text-center">Loading reports...</p>
          </CardContent>
        </Card>
      ) : reports.length === 0 ? (
        <Card>
          <CardContent className="pt-6">
            <div className="text-center space-y-4">
              <AlertCircle className="w-12 h-12 mx-auto text-muted-foreground" />
              <div>
                <h3 className="font-semibold mb-1">No Reports Yet</h3>
                <p className="text-sm text-muted-foreground">
                  Upload company data and run analyses to see reports here.
                </p>
              </div>
              <Button asChild>
                <a href="/upload">Upload Data</a>
              </Button>
            </div>
          </CardContent>
        </Card>
      ) : (
        <>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">Total Reports</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold">{reports.length}</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">High Risk</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold text-red-600">
                  {reports.filter(r => r.riskLevel?.toLowerCase().includes("high")).length}
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">Medium Risk</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold text-yellow-600">
                  {reports.filter(r => r.riskLevel?.toLowerCase().includes("medium")).length}
                </p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">Low Risk</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold text-green-600">
                  {reports.filter(r => r.riskLevel?.toLowerCase().includes("low")).length}
                </p>
              </CardContent>
            </Card>
          </div>

          <div className="space-y-3">
            <h2 className="text-lg font-semibold">Recent Reports</h2>
            <div className="grid gap-3">
              {reports.map((report) => (
                <Card key={report.id} className="hover:shadow-md transition-shadow">
                  <CardContent className="pt-6">
                    <div className="flex items-center justify-between">
                      <div className="flex-1">
                        <div className="flex items-center gap-3 mb-3">
                          <h3 className="font-semibold text-lg">{report.companyName}</h3>
                          <Badge variant={getRiskColor(report.riskLevel)}>
                            {report.riskLevel}
                          </Badge>
                        </div>
                        <p className="text-sm text-muted-foreground mb-4">
                          Generated on {report.date}
                        </p>

                        <div className="grid grid-cols-3 gap-4">
                          <div>
                            <p className="text-xs text-muted-foreground mb-1">Health Score</p>
                            <p className={`text-2xl font-bold ${getScoreColor(report.healthScore)}`}>
                              {report.healthScore.toFixed(1)}
                            </p>
                          </div>
                          <div>
                            <p className="text-xs text-muted-foreground mb-1">Z-Score</p>
                            <p className={`text-2xl font-bold ${getScoreColor(report.zScore * 20)}`}>
                              {report.zScore.toFixed(2)}
                            </p>
                          </div>
                          <div>
                            <p className="text-xs text-muted-foreground mb-1">Investment Score</p>
                            <p className={`text-2xl font-bold ${getScoreColor(report.investmentScore)}`}>
                              {report.investmentScore.toFixed(1)}
                            </p>
                          </div>
                        </div>
                      </div>

                      <div className="flex gap-2">
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => downloadReport(report)}
                        >
                          <Download className="w-4 h-4 mr-1" />
                          Export
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </>
      )}

      <Card className="border-dashed">
        <CardHeader>
          <CardTitle className="text-base flex items-center gap-2">
            <FileDown className="w-4 h-4" />
            About Reports
          </CardTitle>
        </CardHeader>
        <CardContent className="text-sm space-y-2 text-muted-foreground">
          <p>
            Financial reports are automatically generated when you upload and analyze company data. Each report includes:
          </p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Health Score - Overall financial stability rating (0-100)</li>
            <li>Z-Score - Bankruptcy risk using Altman methodology</li>
            <li>Investment Score - Growth and profitability potential (0-100)</li>
            <li>Risk Level - High, Medium, or Low risk classification</li>
          </ul>
          <p className="mt-3">
            Reports are stored locally and can be exported as text files for sharing with stakeholders.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
